export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as CitizenApp } from './CitizenApp';
export { default as AIAssistantPage } from './AIAssistantPage';
export { default as CollectorDashboard } from './CollectorDashboard';
export { default as AuthorityPanel } from './AuthorityPanel';
export { default as SimulationLab } from './SimulationLab';
export { default as EventsPage } from './EventsPage';
export { default as ReportsPage } from './ReportsPage';
